config/routes.rb
Rails.application.routes.draw do
  
  root 'operations#index'
  
  resources :operations do
    resources :cards
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
    belongs_to :operation
    validates :content, presence: true
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  validates :title, presence: true
  
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

before_action :find_operation

def new
    @card = @operation.cards.new
    
end

def edit
    @card = @operation.cards.find(params[:id])
end

def create
    @card = @operation.cards.build(card_params)
    
    if @card.save
        redirect_to operation_path(@operation), notice: "Refresh"
    else
        render :new
    end
end

def update
    @card = @operation.cards.find(params[:id])
    
    if @card.update(card_params)
        redirect_to operation_path(@operation), notice: "Refresh"
    else
        render :edit
    end
end

def destroy 
    @card = @operation.cards.find(params[:id])
    @card.destroy
    redirect_to operation_path(@operation), alert: "Deletion"
    
end

private

def find_operation
    @operation = Operation.find(params[:operation_id])
end

  def card_params
    params.require(:card).permit(:content)
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :find_operation, only: [:show, :edit, :update, :destroy]
  
  def index
    #flash[:notice] = "Servus /// Grüß dich"
    @operations = Operation.all;
  end
  
  def show
    @cards = @operation.cards
  end

  def new
    @operation = Operation.new
  end
  
  def create
    @operation = Operation.create(operation_params)

    if @operation.save
      redirect_to operations_path
    else
      render :new
    end
  end
 
  def edit
    
  end
 
  def update
    if @operation.update(operation_params)
      redirect_to operations_path, notice: "Refresh"
    else
      render :edit
    end
  end

  def destroy
    @operation.destroy
    redirect_to operations_path, alert: "Deletion"
  end
  
  private
  
  def operation_params
    params.require(:operation).permit(:title, :description)
  end
  
  def find_operation
    @operation = Operation.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }
 
    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)
 
    alerts = flash.map do |type, message|
      alert_content = close_button + message
 
      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"
 
      content_tag(:div, alert_content, class: alert_class)
    end
 
    alerts.join("\n").html_safe
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/cards/_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@operation,@card] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h1 class="text-center">Edit Card</h1>
<%= render "form"%>

app/views/cards/new.html.erb
<h1 class="text-center">New card</h1>
<%= render "form"%>

app/views/layouts/_footer.html.erb
<footer class="container" style="margin-top: 120px;">
  <p class="text-center">
    Footer is here<br>
    <span class="glyphicon glyphicon-road" aria-hidden="true"></span> 
     by <a href="#" target=_new>Mosoc Workship</a>
  </p>
  
  
  <nav class = "text-right">
    Bottom Navgation Here
  </nav>
  
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse " role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Problem Maker</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to("Sign in", '#') %> </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Probelm Maker | Junk Breaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container">
    <%= render "layouts/navbar" %>
    <%= notice_message %>
    <%= yield %>
  </div>
  <%= render "layouts/footer"%>
</body>
</html>

app/views/operations/_form.html.erb
 
  <%= simple_form_for @operation do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
 <% end %>

app/views/operations/edit.html.erb
<div>
    <h1>Edit</h1>
    <%= render "form"%>
</div>
    

app/views/operations/index.html.erb
<div>
<h1>Operation List</h1>

<div class = "operation">

    <%= link_to("New Operation", new_operation_path, class: "btn btn-default pull-right") %>

</div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
      </tr>
      </thead>
      
      <tbody>
      <% @operations.each do |operation| %>
        <tr>
        <td>#</td>
        <td> <%= link_to(operation.title, operation_path(operation)) %></td>
        <td> <%= operation.description %></td>
        <td>
             <%= link_to("edit", edit_operation_path(operation), class: "btn btn-sm btn-success") %>
              <%= link_to("delete", operation_path(operation), class: "btn btn-sm btn-primary", method: :delete, data: {confirm: "OK?"}) %>
        </td>    
        </tr>    
      <% end %>
      </tbody>
    </table>      
          
</div>

app/views/operations/new.html.erb
<div>
    <h1>NEW</h1>
    <%= render "form"%>
<div>

app/views/operations/show.html.erb
<div class="col-md-12">
  <div class="operation">
    <%= link_to("Edit", edit_operation_path(@operation), class: "btn btn-primary pull-right")%>
    <%= link_to("New Card", new_operation_card_path(@operation), class: "btn btn-warning pull-right") %>
  </div>
  <h2><%= @operation.title %></h2>
  <p><%= @operation.description %></p>
  
    <table class="table">
    <thead>
      <tr>
        <th>Task</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <td><%= card.content %></td>
          <td>
            <%= link_to("Edit", edit_operation_card_path(card.operation, card),
                        class: "btn btn-default btn-xs")%>
            <%= link_to("Delete", operation_card_path(card.operation, card),
                        class: "btn btn-default btn-xs ", method: :delete, 
                        data: { confirm: "Sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  
</div>